module.exports = {
    NOT_ALLOWED_KEYWORDS: [
        'error',
        'exception',
        'in valid',
        'in_valid',
        'not found',
        'not_found',
        'null',
        'undefined',
    ],
    REGEX: {
        DESCRIPTION: {
            ALPHANUMERIC: 'alphabets & numerics',
            ALPHANUMERIC_WITH_COLON: 'alphabets, numerics & colon',
            ALPHANUMERIC_WITH_DOT: 'alphabets, numerics & dot',
            ALPHANUMERIC_WITH_DOT_UNDERSCORE: 'alphabets, numerics, dot & underscore',
            ALPHANUMERIC_WITH_FWDSLASH_UNDERSCORE: 'alphabets, numerics, underscore & forward slash',
            ALPHANUMERIC_WITH_SPACE: 'alphabets, numerics & space',
            ALPHANUMERIC_WITH_SPACE_DOT: 'alphabets, numerics, space & dot',
            ALPHANUMERIC_WITH_SPACE_UNDERSCORE: 'alphabets, numerics, space & underscore',
            ALPHANUMERIC_WITH_SPECIAL: 'alphabets, numerics & special characters !@#$%^&*()_-{}[]:,./',
            ALPHANUMERIC_WITH_UNDERSCORE: 'alphabates, numerics & underscore',
            BASE64: 'base64',
            INVALID_SPECIAL_CHAR: 'no invalid special characters',
            LATITUDE: 'location latitude',
            LONGITUDE: 'location longitude',
            ONE_LOWERCASE: 'atleast one lowercase',
            ONE_NUMBER: 'at least one number',
            ONE_SPECIALCHAR: 'atleast one special characters',
            ONE_UPPERCASE: 'atleast one uppercase',
            VALID_DOB: 'YYYY-MM-DD',
            VALID_EMAIL: 'valid email',
            VALID_IMEI: 'valid imei',
            VALID_MAC: 'valid mac',
            VALID_PHONECOUNTRYCODE: 'phone country code',
            VALID_TIMEZONE_HOUR: 'timezone (+05:30)',
            VALID_TIMEZONE_REGION: 'timezone (Asia/Kolkata)',
        },
        EXPRESSION: {
            ALPHANUMERIC: /^[a-zA-Z0-9]+$/i,
            ALPHANUMERIC_WITH_COLON: /^[a-zA-Z0-9:]+$/i,
            ALPHANUMERIC_WITH_DOT: /^[a-zA-Z0-9.]+$/i,
            ALPHANUMERIC_WITH_DOT_UNDERSCORE: /^[\w.]+$/i,
            ALPHANUMERIC_WITH_FWDSLASH_UNDERSCORE: /^[\w\/]+$/i,
            ALPHANUMERIC_WITH_SPACE: /^[a-zA-Z0-9 ]+$/i,
            ALPHANUMERIC_WITH_SPACE_DOT: /^[a-zA-Z0-9. ]+$/i,
            ALPHANUMERIC_WITH_SPACE_UNDERSCORE: /^[\w ]+$/i,
            ALPHANUMERIC_WITH_SPECIAL: /^[\w !@#$%^&*(),."':{}\\[\]\/\-]+$/i,
            ALPHANUMERIC_WITH_UNDERSCORE: /^[\w]+$/i,
            BASE64: /^([0-9a-zA-Z+/]{4})*(([0-9a-zA-Z+/]{2}==)|([0-9a-zA-Z+/]{3}=))?$/,
            INVALID_SPECIAL_CHAR: /^[\w!@#$%^&*()_\-+=]+$/i,
            LATITUDE: /^([-+]?)([\d]{1,2})(((\.)(\d+)))(\s*)$/,
            LONGITUDE: /^(([-+]?)([\d]{1,3})((\.)(\d+))?)$/,
            ONE_LOWERCASE: /[A-Z]/,
            ONE_NUMBER: /[a-z]/,
            ONE_SPECIALCHAR: /\d/,
            ONE_UPPERCASE: /[!@#$%^&*()_\-+=]+/,
            VALID_DOB: /^(\d{4})-(\d{2})-(\d{2})$/,
            VALID_EMAIL: /^([A-Za-z0-9_\-\.])+\@([A-Za-z0-9_\-\.])+\.([A-Za-z]{2,4})$/i,
            VALID_IMEI: /^([0-9]{15})+$/,
            VALID_MAC: /^[0-9a-z]{1,2}([:])(?:[0-9a-z]{1,2}\1){4}[0-9a-z]{1,2}$/i,
            VALID_PHONECOUNTRYCODE: /^(\+?\d{1,7}|\d{1,8})$/i,
            VALID_TIMEZONE_HOUR: /^([\+\-]{1}(\d{1,2}){1}:{1}(\d{2}){1})+$/i,
            VALID_TIMEZONE_REGION: /^([a-zA-Z]+(\/){1}[a-zA-Z_]+)+$/i,
        },
    },
};
